name: Adnroid CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: |
        cd android
        chmod +x gradlew
    - name: Build with Gradle
      run: | 
        cd android
        ./gradlew syncDebugLibJars
